export const cities = [
    { value: "Makkah al Mukarramah", name: "مكة المكرمة" },
    { value: "Riyadh", name: "الرياض" },
    { value: "Jeddah", name: "جدة" },
    { value: "Dammam", name: "الدمام" },
    { value: "Madinah", name: "المدينة المنورة" },
    { value: "Khobar", name: "الخبر" },
    { value: "Abha", name: "أبها" },
    { value: "Taif", name: "الطائف" },
    { value: "Buraidah", name: "بريدة" },
    { value: "Tabuk", name: "تبوك" },
    { value: "Hail", name: "حائل" },
    { value: "Najran", name: "نجران" },
    { value: "Jazan", name: "جازان" },
    { value: "Al Qassim", name: "القصيم" },
    { value: "Yanbu", name: "ينبع" },
    { value: "Al Jubail", name: "الجبيل" },
    { value: "Arar", name: "عرعر" },
    { value: "Sakaka", name: "سكاكا" },
    { value: "Unaizah", name: "عنيزة" },
    { value: "Al Khobar", name: "الخبر" },
    { value: "Al Hofuf", name: "الهفوف" },
    { value: "Dhahran", name: "الظهران" },
];